const member = {
    dataMember: {

        Odi: {
            profile: "/odiProfile.png",
            nama: "Audrey Glacia Cipta",
            bod: "18/03/2001",
            horoskop: "Sagitarius",
            tinggi: "180",
            callsign: "Odi",
            email: "audrey.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Tasikmalaya",
            role: "member",
            instagram: "www.google.com",
            twitter: "www.google.com",
            tiktok: "www.google.com",
        },
        aurell: {
            profile: "/aurellProfile.png",
            nama: "Syahla Nazmi NoorAurell",
            bod: "18/03/2001",
            horoskop: "Sagitarius",
            tinggi: "180",
            callsign: "Ulell",
            email: "audrey.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Tasikmalaya",
            role: "member",
            instagram: "www.google.com",
            twitter: "www.google.com",
            tiktok: "www.google.com",
        },
        nabi: {
            profile: "/nabiProfile.png",
            nama: "Nabila Agnia Putri",
            bod: "18/03/2001",
            horoskop: "Sagitarius",
            tinggi: "180",
            callsign: "Nabi",
            email: "audrey.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Tasikmalaya",
            role: "member",
            instagram: "www.google.com",
            twitter: "www.google.com",
            tiktok: "www.google.com",
        },
        nara: {
            profile: "/naraProfile.png",
            nama: "Syahla Nazmi NoorAurell",
            bod: "18/03/2001",
            horoskop: "Sagitarius",
            tinggi: "180",
            callsign: "Nara",
            email: "audrey.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Tasikmalaya",
            role: "member",
            instagram: "www.google.com",
            twitter: "www.google.com",
            tiktok: "www.google.com",
        },
        Vio: {
            profile: "/vioProfile.png",
            nama: "Viola Erlanda Cipta",
            bod: "18/03/2001",
            horoskop: "Sagitarius",
            tinggi: "180",
            callsign: "Vio",
            email: "viola.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Tasikmalaya",
            role: "captain",
            instagram: "www.google.com",
            twitter: "www.google.com",
            tiktok: "www.google.com",
        },
    },

};

export {
    member,
};