const member = {
    dataMember: {

        Odi: {
            profile: "/odiProfile.png",
            nama: "Audrey Glacia Cipta",
            bod: "18/03/2001",
            horoskop: "Sagitarius",
            tinggi: "180",
            callsign: "Odi",
            email: "audrey.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Tasikmalaya",
            role: "member",
            instagram: "audreyygl_",
            twitter: "Oddyeo",
            message: "Semangat !!. Jangan pernah Putus Asa >.<",
            tiktok: "-",
        },
        Ulell: {
            profile: "/aurellProfile.png",
            nama: "Syahla Nazmi NoorAurell",
            bod: "18/03/2001",
            horoskop: "Sagitarius",
            tinggi: "180",
            callsign: "Ulell",
            email: "audrey.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Tasikmalaya",
            role: "member",
            instagram: "__babyaurell",
            twitter: "babyyaurell",
            tiktok: "-",
            message: "Senang Bertemu Kalian Semua >.<",
            videojiko: "/video/example.mp4",
        },
        Nabi: {
            profile: "/nabiProfile.png",
            nama: "Nabila Agnia Putri",
            bod: "18/03/2001",
            horoskop: "Sagitarius",
            tinggi: "180",
            callsign: "Nabi",
            email: "audrey.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Tasikmalaya",
            role: "member",
            instagram: "hola.bilaaa",
            twitter: "urbabylaa",
            message: "Diam bukan berarti aku ga perhatian loh >.<",
            tiktok: "www.google.com",
        },
        Nara: {
            profile: "/naraProfile.png",
            nama: "Nazwa Zahra",
            bod: "04 Mei 2006",
            horoskop: "Leo",
            tinggi: "180",
            callsign: "Nara",
            email: "nara.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Bali",
            role: "member",
            instagram: "hynnaraa",
            twitter: "hynnaraaa",
            message: "Senyumku mengalihkan seluruh duniamu >.<",
            tiktok: "",
        },
        Vio: {
            profile: "/vioProfile.png",
            nama: "Viola Erlanda Cipta",
            bod: "18/03/2001",
            horoskop: "Sagitarius",
            tinggi: "180",
            callsign: "Vio",
            email: "viola.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Tasikmalaya",
            role: "captain",
            instagram: "shinviooo",
            twitter: "violaercipta",
            message: "Si Pemanah yang akan memanah hatimu >.<",
            tiktok: "www.google.com",
        },

    },


};

export {
    member,
};